name: Build and Release OCRmyPDF (Windows)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Create and activate venv, install dependencies
        run: |
          uv venv .venv
          .venv\Scripts\activate
          uv pip install -r pyproject.toml
          uv pip install nuitka

      - name: Build with Nuitka
        run: |
          .venv\Scripts\activate
          python -m nuitka --standalone --show-memory --show-progress --show-scons --nofollow-imports --windows-disable-console --windows-icon-from-ico=app_icon.ico --output-dir=dist --enable-plugin=tk-inter --follow-import-to=OCRmyPDF --include-data-file=app_icon.ico=app_icon.ico --include-data-dir=.venv/Lib/site-packages/ocrmypdf/data=ocrmypdf/data --include-package=ocrmypdf,pdfminer,pikepdf  --output-filename=OCRmyPDF.exe OCRmyPDF/main.py
        shell: pwsh

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: OCRmyPDF-win
          path: dist/**

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/OCRmyPDF.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
